### ISSUE TITLE
Empty arrray causes a parser error

### ISSUE THREAD

**Issue by treahard** [grafi-tt/lunajson#29]
The simple json example below which has an empty array [] causes a" parse error at 44: no closing bracket of an object"

Empty arrays are permitted (although not very useful).

{
  "parmValue": "NONE",
  "emptyArray": []
}

**Comment by treahard** [comment]
I have a simple fix for this.  Do you prefer a pull request?

**Comment by Benjamin-Dobell** [comment]
This issue probably should have noted that it's only SAX decoder that fails to handle empty arrays. It fails to handle empty objects as well. PR with tests + fix inbound.

**Comment by grafi-tt** [comment]
Sorry, I didn't noticed the issue. I'll look the PR soon. Thank you very much!

**Comment by grafi-tt** [comment]
Thank you very much @treahard and @Benjamin-Dobell  !

The issue is fixed in 1.2.3 release.
