### ISSUE TITLE
"integer" JSON value become float in lua.

### ISSUE THREAD

**Issue by tomgrean** [grafi-tt/lunajson#5]
For example, the JSON string `{"code":20, "val":"abcd"}`
I'm using lua 5.3.4, and want to parse it and write to a .conf file, as a configuration:
```
code=20
val=abcd
```
but now the resulting configuration file is
```
code=20.0
val=abcd
```
the trailing ".0" makes the program fail to start up correctly.
I think it is related to lua5.3's new integer type feature. I think we can add a math.type() or math.tointeger() check with JSON number.

**Comment by grafi-tt** [comment]
@tomgrean Sorry for having left this problem for long time. Now it's fixed on master. I will release version 1.2 with some other fixes.

**Comment by tomgrean** [comment]
My pleasure to help.
Great to see the improvements :)
